### ISSUE TITLE
Queue cleaner bug

### ISSUE THREAD

**Issue by kabachook** [codex-team/domain-checker#20]
Traceback:
```
Queue cleaner error
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Timeout.cleanQueues [as _onTimeout] (domain-checker/backend/src/workers/responder/index.js:44:14)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
```

**Comment by kabachook** [comment]
Closed by #22
